# four node (three workers) cluster config
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
  labels:
    node-type: infra
- role: worker
  labels:
    node-type: app
- role: worker
  labels:
    node-type: app

