apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpa-nginx-deploy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeSelector:
        node-type: app 
      containers:
      - name: nginx
        image: docker.io/nginx:latest 
        ports:
        - containerPort: 80
        resources:    
          requests:
            cpu: 100m
          limits:
            cpu: 500m
